name: youtube_trends_flutter
description: "A YouTube trends analysis application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  idb_shim: ^2.6.5+1
  path: ^1.8.3
  fl_chart: ^0.66.0
  http: ^1.1.0
  intl: ^0.19.0
  google_fonts: ^6.1.0
  url_launcher: ^6.1.14
  shared_preferences: ^2.5.3
  drift: ^2.13.0
  sqlite3: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.13.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true 